steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'europe-west4-docker.pkg.dev/$PROJECT_ID/pairs-trading-backend/app:$COMMIT_SHA', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'europe-west4-docker.pkg.dev/$PROJECT_ID/pairs-trading-backend/app:$COMMIT_SHA']
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
  - 'run'
  - 'deploy'
  - 'pairs-trading-backend'
  - '--image'
  - 'europe-west4-docker.pkg.dev/$PROJECT_ID/pairs-trading-backend/app:$COMMIT_SHA'
  - '--region'
  - 'europe-west4'
  - '--platform'
  - 'managed'
options:
  logging: CLOUD_LOGGING_ONLY
images:
- 'europe-west4-docker.pkg.dev/$PROJECT_ID/pairs-trading-backend/app:$COMMIT_SHA'