services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - PORT=
      - DB_USER=
      - DB_PASS=
      - DB_NAME=
      - INSTANCE_CONNECTION_NAME=
      - GOOGLE_CLIENT_ID=
      - GOOGLE_CLIENT_SECRET=
      - JWT_SECRET=
      - GOOGLE_REDIRECT_URL_HOST=
      - POLYGON_API_KEY=
      - QUANT_SERVICE_HOST=
      - QUANT_SERVICE_API_KEY=
    volumes:
      - /tmp/cloudsql:/cloudsql